### PR TITLE
Start of version checking

### PR DESCRIPTION
**Pull request by TheGreyDiamond**
Start of version info. 
# DO NOT MERGE YET

### CODE REVIEW

**Comment by XilefTech** [comment]
U sure that you want to include the update of your settings.json? And I think we have to use ujson because micropython...

**Comment by TheGreyDiamond** [comment]
I changed some shit, this uses ujson now, also removed old files.

**Comment by XilefTech** [comment]
Will this ever happen?

**Comment by XilefTech** [comment]
gonna close this for now, until you start working on it again....

**Comment by TheGreyDiamond** [comment]
Implemented in #30

**Pull request closed without merging**
